<?php
namespace console\modules\chat;

use yii\base\Module;

class ChatModule extends Module
{
    public $controllerNamespace = 'console\modules\chat\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}